class AppTexts {
  static const String toDoListDailyTask = "ToDo List\n Daily Task";
  static const String descriptionOnBoarding =
      "This productive tool is designed to help\nyou better manage your task\nproject-wise conveniently!";
  static const String letStart = "Let’s Start";
  static const String addPhoto = "Add Photo";
  static const String updatePhoto = "Update photo";
  static const String yourName = "Your Name";
  static const String enterYourName = "Enter Your Name";
  static const String getStarted = "Get Started";
  static const String gallery = "Gallery";
  static const String camera = "Camera";
  static const String hello = "Hello!";
  static const String done = "Done";
  static const String delete = "Delete";
  static const String doneTasks = "Done Tasks";
  static const String archivedTasks = "Archived Tasks";
  static const String addTask = "Add Task";
  static const String yes = "Yes";
  static const String cancel = "Cancel";
  static const String taskName = "Task Name";
  static const String enterTaskName = "Enter The Task Name";
  static const String description = "Description";
  static const String enterTaskDescription = "Enter The Task Description";
  static const String startDate = "Start Date";
  static const String endDate = "End Date";
  static const String addTime = "Add Time";
  static const String enterStartDate = "Enter The Start Date";
  static const String enterEndDate = "Enter The End Date";
  static const String setTimeForTask = "Set a Time For The Task";
  static const String taskDetails = "Task Details";
  static const String archive = "Archive";
  static const String unarchive = "Unarchive";
  static const String lightMode = "Light Mode";
  static const String darkMode = "Dark Mode";
  static const String titleAlertDialog = "Are you sure you want to delete\nthis task?";
  static const String settingsBox = "settingsBox";
  static const String switchValue = "switchValue";
}
